import '@dhis2/cypress-commands'

// Add additional support functions here
import './all'
import './clickWith'
import './find'
import './get'
import './getAll'
import './getPositionsBySelectors'
import './uploadMultipleFiles'
import './uploadSingleFile'
import './visitStory'
import './org_unit_tree/index'
import './getFormValue'
import './selectSelectNthOption'
import './verifyFormValue'
