export { default as CompleteRegistrationPage } from './complete-registration.js'
export { default as ConfirmEmailPage } from './confirm-email.js'
export { default as CreateAccountPage } from './create-account.js'
export { default as LoginPage } from './login.js'
export { default as PasswordResetRequestPage } from './password-reset-request.js'
export { default as PasswordUpdatePage } from './password-update.js'
