/*
 * For backwards compatibility we export the components that were
 * available in `ui-core` here.
 */
export { default as AlertBar } from '@dhis2/ui-alert-bar'
export { default as AlertStack } from '@dhis2/ui-alert-stack'
export { default as Button } from '@dhis2/ui-button'
export { default as Box } from '@dhis2/ui-box'
export { default as ButtonStrip } from '@dhis2/ui-button-strip'
export { default as Card } from '@dhis2/ui-card'
export { default as CenteredContent } from '@dhis2/ui-centered-content'
export { default as Checkbox } from '@dhis2/ui-checkbox'
export { default as Chip } from '@dhis2/ui-chip'
export { default as CircularLoader } from '@dhis2/ui-circular-loader'
export { default as ComponentCover } from '@dhis2/ui-component-cover'
export { default as CssReset } from '@dhis2/ui-css-reset'
export { default as CssVariables } from '@dhis2/ui-css-variables'
export { default as Divider } from '@dhis2/ui-divider'
export { default as DropdownButton } from '@dhis2/ui-dropdown-button'
export { default as Field } from '@dhis2/ui-field'
export { default as FieldSet } from '@dhis2/ui-field-set'
export { default as FileInput } from '@dhis2/ui-file-input'
export { default as FileList, FileListItem, FileListPlaceholder } from '@dhis2/ui-file-list'
export { default as FlyoutMenu } from '@dhis2/ui-flyout-menu'
export { default as Help } from '@dhis2/ui-help'
export { default as Input } from '@dhis2/ui-input'
export { default as IntersectionDetector } from '@dhis2/ui-intersection-detector'
export { default as Label } from '@dhis2/ui-label'
export { default as Layer, useLayerContext } from '@dhis2/ui-layer'
export { default as Legend } from '@dhis2/ui-legend'
export { default as LinearLoader } from '@dhis2/ui-linear-loader'
export { default as Logo, LogoIcon, LogoIconWhite, LogoWhite } from '@dhis2/ui-logo'
export { default as Menu, MenuDivider, MenuItem, MenuSectionHeader } from '@dhis2/ui-menu'

export { Modal } from './Modal/Modal.js'
export { ModalActions } from './ModalActions/ModalActions.js'
export { ModalContent } from './ModalContent/ModalContent.js'
export { ModalTitle } from './ModalTitle/ModalTitle.js'
export { MultiSelect } from './MultiSelect/MultiSelect.js'
export { MultiSelectOption } from './MultiSelectOption/MultiSelectOption.js'
export { Node } from './Node/Node.js'
export { NoticeBox } from './NoticeBox/NoticeBox.js'
export { Popover } from './Popover/Popover.js'
export { Popper } from './Popper/Popper.js'
export { Radio } from './Radio/Radio.js'
export { Required } from './Required/Required.js'
export { SingleSelect } from './SingleSelect/SingleSelect.js'
export { SingleSelectOption } from './SingleSelectOption/SingleSelectOption.js'
export { StackedTable } from './StackedTable/StackedTable.js'
export { StackedTableBody } from './StackedTable/StackedTableBody.js'
export { StackedTableCell } from './StackedTable/StackedTableCell.js'
export { StackedTableCellHead } from './StackedTable/StackedTableCellHead.js'
export { StackedTableFoot } from './StackedTable/StackedTableFoot.js'
export { StackedTableHead } from './StackedTable/StackedTableHead.js'
export { StackedTableRow } from './StackedTable/StackedTableRow.js'
export { StackedTableRowHead } from './StackedTable/StackedTableRowHead.js'
export { SplitButton } from './SplitButton/SplitButton.js'
export { Switch } from './Switch/Switch.js'
export { Tab } from './Tab/Tab.js'
export { TabBar } from './TabBar/TabBar.js'
export { Table } from './Table/Table.js'
export { TableBody } from './Table/TableBody.js'
export { TableCell } from './Table/TableCell.js'
export { TableCellHead } from './Table/TableCellHead.js'
export { TableFoot } from './Table/TableFoot.js'
export { TableHead } from './Table/TableHead.js'
export { TableRow } from './Table/TableRow.js'
export { TableRowHead } from './Table/TableRowHead.js'
export { Tag } from './Tag/Tag.js'
export { TextArea } from './TextArea/TextArea.js'
export { Tooltip } from './Tooltip/Tooltip.js'
