export { ADD_MODE, RANGE_MODE, REPLACE_MODE } from './modes.ts'
export { findOptionIndex } from './find-option-index.ts'
export { getModeByModifierKey } from './get-mode-by-modifier-key.ts'
export { isOption } from './is-option.ts'
export type { TransferOptionObject } from './is-option.ts'
export { toggleValue } from './toggle-value.ts'
