name: 'DHIS2'

on:
    push:
        branches:
            - master

jobs:
    process:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install

            - name: Lint
              run: yarn lint

            - name: Build
              run: yarn build

            - name: Publish
              run: npx @dhis2/cli-utils release --publish npm
              env:
                  GIT_AUTHOR_NAME: '@dhis2-bot'
                  GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
                  GIT_COMMITTER_NAME: '@dhis2-bot'
                  GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
                  GH_TOKEN: ${{secrets.GH_TOKEN}}
        env:
            CI: true
